name: namer_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: ^3.1.1

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.3
  flutter_launcher_icons: "^0.13.1"
  english_words: ^4.0.0
  flutter_svg: ^2.0.9
  shared_preferences: ^2.0.8
  provider: ^5.0.0
  image_picker: ^1.1.1
  path_provider: ^2.1.3
  firebase_core: ^2.26.0
  firebase_auth: ^4.17.7
  google_sign_in: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icon/icon.png
    - assets/profilepics/
    - assets/ic_launcher.png
    - assets/meals/
    - assets/glass.png
    - assets/bell.png
    - assets/bottle.png
  
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/icon/icon.png"
    background_color: "#FFFFFF"
    theme_color: "#HDIELS"
  windows:
    generate: true
    image_path: "assets/icon/icon.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/icon/icon.png"